server:
  port: 9003
spring:
  application:
    name: index
    # 目前写在nacos配置里
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/index_source
#    username: root
#    password: renzhe2zhuzhu
  cloud:
    nacos:
      discovery:
        # 配置中心服务器地址，也就是Nacos地址,这里用nginx做LB
        server-addr: 192.168.2.101:80
        ephemeral: false
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
management:
  endpoints:
    web:
      exposure:
        include: '*'